### ISSUE TITLE
SEO touch up checklist

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/foodouken.com#71]
https://app.neilpatel.com/en/seo_analyzer/site_audit?domain=foodouken.com&submit=Analyze+Website

- [x] add sitemap

- [x]  make our first title "bang bang bakery" an H1

- [x] make our description paragpaph a p so it is recongized as tyeh description and word count.

- [ ] Troubleshoot missing meta description

- [x] structured data missing

**Comment by paulchrisluke** [comment]
@mort3za how do you add a sitemap?

**Comment by mort3za** [comment]
@paulchrisluke for vKirirom added the routes inside sitemap manually (just main routes to help google find other routes). Just check Search Console, If there was no sitemap, submit the link.

**Comment by paulchrisluke** [comment]
structured data is now working. Last bit is getting our meta tags in place. 

In vkirirom, we have static meta tags for all pages (good for twitter and facebook), and we update those tags by vue-meta by dynamic data (both meta tags and jsonld).
